package report

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"

	"github.com/shahneil76/kubectl-inventory/pkg/audit"
)

// Meta carries export context printed on the cover page.
type Meta struct {
	Context   string
	Namespace string
	Generated time.Time
}

// GeneratePDF builds a kubectl-inventory posture report PDF.
func GeneratePDF(report *audit.PostureReport, meta Meta) ([]byte, error) {
	if report == nil {
		return nil, fmt.Errorf("nil posture report")
	}
	if meta.Generated.IsZero() {
		meta.Generated = time.Now()
	}

	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetMargins(16, 16, 16)
	pdf.AliasNbPages("")
	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Helvetica", "I", 8)
		pdfCell(pdf, 0, 8, fmt.Sprintf("kubectl-inventory posture report | page %d/{nb}", pdf.PageNo()), "", 0, "C", false, 0, "")
	})

	writeCover(pdf, report, meta)
	writeExecutiveSummary(pdf, report)
	writeActionQueue(pdf, report)
	writeNamespaceHeatmap(pdf, report)
	writeFindingsAppendix(pdf, report, meta)

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func writeCover(pdf *fpdf.Fpdf, report *audit.PostureReport, meta Meta) {
	pdf.AddPage()
	pdf.SetFont("Helvetica", "B", 22)
	pdfCell(pdf, 0, 12, "kubectl-inventory", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 16)
	pdfCell(pdf, 0, 10, "Cluster Posture Report", "", 1, "L", false, 0, "")
	pdf.Ln(4)

	pdf.SetFont("Helvetica", "", 11)
	lines := []string{
		fmt.Sprintf("Context: %s", valueOr(meta.Context, "unknown")),
		fmt.Sprintf("Scope: %s", scopeLabel(meta.Namespace)),
		fmt.Sprintf("Generated: %s", meta.Generated.Format(time.RFC3339)),
		fmt.Sprintf("Posture Index: %d (%s)", report.Posture.Score, report.Posture.Grade),
		fmt.Sprintf("Must-fix: %d   Advisory: %d", report.Summary.Danger, report.Summary.Warning),
	}
	if report.CompoundFindings > 0 {
		lines = append(lines, fmt.Sprintf("Compound inventory risks: %d", report.CompoundFindings))
	}
	for _, line := range lines {
		pdfCell(pdf, 0, 7, line, "", 1, "L", false, 0, "")
	}

	pdf.Ln(6)
	pdf.SetFont("Helvetica", "I", 10)
	pdfMultiCell(pdf, 0, 5, report.Posture.Description, "", "L", false)
	pdf.Ln(4)
	pdf.SetFont("Helvetica", "", 9)
	pdfMultiCell(pdf, 0, 4, "This report combines best-practice checks with inventory-native lifecycle signals (dangling owners, stuck finalizers, GitOps drift). It is generated by kubectl-inventory, not a generic policy scanner export.", "", "L", false)
}

func writeExecutiveSummary(pdf *fpdf.Fpdf, report *audit.PostureReport) {
	pdf.AddPage()
	sectionTitle(pdf, "Executive summary")

	headers := []string{"Lens", "Must-fix", "Advisory"}
	widths := []float64{80, 40, 40}
	tableHeader(pdf, headers, widths)

	labels := map[string]string{
		audit.CategorySecurity:    "Hardening",
		audit.CategoryReliability: "Resilience",
		audit.CategoryEfficiency:  "Right-sizing",
	}
	for _, cat := range []string{audit.CategorySecurity, audit.CategoryReliability, audit.CategoryEfficiency} {
		cs := report.Summary.Categories[cat]
		tableRow(pdf, []string{labels[cat], fmt.Sprintf("%d", cs.Danger), fmt.Sprintf("%d", cs.Warning)}, widths)
	}

	if report.InventoryFindings > 0 {
		pdf.Ln(4)
		pdf.SetFont("Helvetica", "", 10)
		pdfCell(pdf, 0, 6, fmt.Sprintf("Inventory-native signals included: %d findings not available in generic audit-only tools.", report.InventoryFindings), "", 1, "L", false, 0, "")
	}
}

func writeActionQueue(pdf *fpdf.Fpdf, report *audit.PostureReport) {
	if len(report.ActionQueue) == 0 {
		return
	}
	pdf.AddPage()
	sectionTitle(pdf, "Priority action queue")

	pdf.SetFont("Helvetica", "", 9)
	pdfMultiCell(pdf, 0, 4, "Ranked by impact score - compound inventory+audit risks surface first.", "", "L", false)
	pdf.Ln(2)

	limit := len(report.ActionQueue)
	if limit > 15 {
		limit = 15
	}
	for i := 0; i < limit; i++ {
		item := report.ActionQueue[i]
		pdf.SetFont("Helvetica", "B", 10)
		title := fmt.Sprintf("#%d  %s/%s  [%s]", item.Rank, item.Kind, item.Name, strings.ToUpper(item.Severity))
		pdfCell(pdf, 0, 6, title, "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 9)
		pdfMultiCell(pdf, 0, 4, fmt.Sprintf("%s - %s", item.Title, item.Reason), "", "L", false)
		if item.Namespace != "" {
			pdfCell(pdf, 0, 5, "Namespace: "+item.Namespace, "", 1, "L", false, 0, "")
		}
		pdf.Ln(1)
	}
}

func writeNamespaceHeatmap(pdf *fpdf.Fpdf, report *audit.PostureReport) {
	if len(report.NamespacePostures) == 0 {
		return
	}
	pdf.AddPage()
	sectionTitle(pdf, "Namespace posture heatmap")

	headers := []string{"Namespace", "Grade", "Score", "Must-fix", "Advisory"}
	widths := []float64{70, 20, 20, 25, 25}
	tableHeader(pdf, headers, widths)

	limit := len(report.NamespacePostures)
	if limit > 25 {
		limit = 25
	}
	for i := 0; i < limit; i++ {
		ns := report.NamespacePostures[i]
		tableRow(pdf, []string{
			ns.Namespace,
			ns.Grade,
			fmt.Sprintf("%d", ns.Score),
			fmt.Sprintf("%d", ns.MustFix),
			fmt.Sprintf("%d", ns.Advisory),
		}, widths)
	}
}

func writeFindingsAppendix(pdf *fpdf.Fpdf, report *audit.PostureReport, meta Meta) {
	pdf.AddPage()
	sectionTitle(pdf, "Findings appendix")

	pdf.SetFont("Helvetica", "", 8)
	pdfCell(pdf, 0, 5, fmt.Sprintf("Showing up to 200 findings | scope: %s", scopeLabel(meta.Namespace)), "", 1, "L", false, 0, "")
	pdf.Ln(2)

	limit := len(report.EnrichedFindings)
	if limit > 200 {
		limit = 200
	}
	for i := 0; i < limit; i++ {
		ef := report.EnrichedFindings[i]
		checkMeta := report.Checks[ef.CheckID]
		title := checkMeta.Title
		if title == "" {
			title = ef.CheckID
		}

		pdf.SetFont("Helvetica", "B", 9)
		hdr := fmt.Sprintf("%s/%s [%s] - %s", ef.Kind, ef.Name, strings.ToUpper(ef.Severity), title)
		pdfCell(pdf, 0, 5, truncate(hdr, 95), "", 1, "L", false, 0, "")

		pdf.SetFont("Helvetica", "", 8)
		if ef.Namespace != "" {
			pdfCell(pdf, 0, 4, "ns: "+ef.Namespace+"  lens: "+ef.Lens, "", 1, "L", false, 0, "")
		}
		if ef.InventorySignal != "" && ef.InventorySignal != "CLEAN" {
			pdfCell(pdf, 0, 4, "inventory signal: "+ef.InventorySignal, "", 1, "L", false, 0, "")
		}
		pdfMultiCell(pdf, 0, 4, truncate(ef.Message, 140), "", "L", false)
		if checkMeta.Remediation != "" {
			pdf.SetFont("Helvetica", "I", 8)
			pdfMultiCell(pdf, 0, 4, "fix: "+truncate(checkMeta.Remediation, 140), "", "L", false)
		}
		pdf.Ln(1)

		if pdf.GetY() > 270 {
			pdf.AddPage()
		}
	}
}

func sectionTitle(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 14)
	pdfCell(pdf, 0, 8, title, "", 1, "L", false, 0, "")
	pdf.Ln(2)
}

func tableHeader(pdf *fpdf.Fpdf, headers []string, widths []float64) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(230, 230, 230)
	for i, h := range headers {
		pdfCell(pdf, widths[i], 7, h, "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)
}

func tableRow(pdf *fpdf.Fpdf, cells []string, widths []float64) {
	pdf.SetFont("Helvetica", "", 9)
	for i, c := range cells {
		pdfCell(pdf, widths[i], 6, truncate(c, 40), "1", 0, "L", false, 0, "")
	}
	pdf.Ln(-1)
}

func truncate(s string, max int) string {
	s = pdfText(s)
	runes := []rune(s)
	if len(runes) <= max {
		return s
	}
	return string(runes[:max-3]) + "..."
}

func valueOr(v, fallback string) string {
	if v == "" {
		return fallback
	}
	return v
}

func scopeLabel(ns string) string {
	if ns == "" || ns == "*" {
		return "all namespaces"
	}
	return ns
}
